x-service-templates:
  payment-gateway: &payment-gateway
    build:
      dockerfile: Dockerfile
      no_cache: true
    hostname: api01
    networks:
      - payment-processor

services:
  api01:
    <<: *payment-gateway
    container_name: api01
    hostname: api01
    ports:
      - "8080:8080"

  api02:
    <<: *payment-gateway
    container_name: api02
    hostname: api02
    ports:
      - "8081:8080"

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"

networks:
  payment-processor:
    external: true
