spring.application.name=payment-gateway
spring.threads.virtual.enabled=true
server.undertow.threads.io=1
server.undertow.threads.worker=8

spring.datasource.url=jdbc:postgresql://rinha:5432/rinha
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.driver-class-name=org.postgresql.Driver

#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.springframework.jdbc.core=TRACE
#logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
#logging.level.org.springframework.jdbc.datasource=DEBUG

MAX_PAYMENTS_THREADS=200
pagamento.processor.default.url=http://payment-processor-default:8080
pagamento.processor.fallback.url=http://payment-processor-fallback:8080

#logging.level.org.springframework.web.client.RestTemplate=DEBUG
